import { NextResponse } from 'next/server'
export const runtime = 'nodejs'
import { db } from '@/lib/db'
import { getAuthenticatedUserId } from '@/lib/user'

/**
 * GET /api/digest/today — returns today's daily digest for the current user,
 * if one exists. Generated by /api/cron/daily-digest (Vercel Cron, 06:00 UTC).
 * Returns null if no digest exists for today (e.g. cron hasn't run yet, or
 * there was nothing to digest).
 */
export async function GET() {
  try {
    const userId = await getAuthenticatedUserId()
    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const today = new Date(new Date().toDateString())
    const digest = await db.dailyDigest.findUnique({
      where: { userId_date: { userId, date: today } },
      select: { content: true, date: true },
    })

    return NextResponse.json({ digest: digest?.content ?? null, date: digest?.date?.toISOString() ?? null })
  } catch (err) {
    console.error('[digest.today]', err)
    return NextResponse.json({ error: 'Failed to load digest' }, { status: 500 })
  }
}
