"use client";

import { useEffect, useRef } from "react";
import { usePlayerStore } from "@/lib/player-store";

/**
 * Audio engine — drives real playback via stored MP3 audio (generated by
 * Edge TTS on the server), with a speechSynthesis fallback for chapters
 * whose generation is pending or has failed.
 *
 * Strategy:
 *  - When a chapter's status is 'ready' and it has an audioUrl: play it with
 *    a real <audio> element. Native currentTime/duration/seeking all work.
 *  - When status is 'pending': show "Narrating…" state, call the generate
 *    route, then play once it resolves.
 *  - If generation fails: fall back to speechSynthesis live-reading for that
 *    chapter specifically (using the same paragraph-queue approach).
 *  - Pre-generate the next chapter in the background once playback starts.
 *  - Progress is persisted via PATCH /api/audiobooks/[id] every 5 seconds.
 */
export function useAudioEngine() {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const rafRef = useRef<number | null>(null);
  const lastTickRef = useRef<number>(0);

  // speechSynthesis state (for fallback)
  const paragraphIndexRef = useRef<number>(0);
  const paragraphsRef = useRef<string[]>([]);
  const speakingLiveRef = useRef<boolean>(false);

  const currentAudiobook = usePlayerStore((s) => s.currentAudiobook);
  const chapters = usePlayerStore((s) => s.chapters);
  const chapterIndex = usePlayerStore((s) => s.chapterIndex);
  const isPlaying = usePlayerStore((s) => s.isPlaying);
  const playbackRate = usePlayerStore((s) => s.playbackRate);
  const volume = usePlayerStore((s) => s.volume);
  const muted = usePlayerStore((s) => s.muted);
  const sleepTimerEndsAt = usePlayerStore((s) => s.sleepTimerEndsAt);

  const setCurrentTime = usePlayerStore((s) => s.setCurrentTime);
  const setDuration = usePlayerStore((s) => s.setDuration);
  const pause = usePlayerStore((s) => s.pause);
  const nextChapter = usePlayerStore((s) => s.nextChapter);
  const setNarrating = usePlayerStore((s) => s.setNarrating);
  const setUsingLiveNarration = usePlayerStore((s) => s.setUsingLiveNarration);
  const updateChapterStatus = usePlayerStore((s) => s.updateChapterStatus);

  // Create audio element once
  useEffect(() => {
    const a = new Audio();
    a.preload = "auto";
    audioRef.current = a;
    return () => {
      a.pause();
      a.src = "";
      if (typeof window !== "undefined" && window.speechSynthesis) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  /** Split chapter text into paragraph-sized chunks for speech synthesis. */
  function splitIntoParagraphs(text: string): string[] {
    const rawParas = text.split(/\n\s*\n/).map(p => p.trim()).filter(Boolean);
    const result: string[] = [];
    for (const para of rawParas) {
      if (para.length <= 1200) {
        result.push(para);
      } else {
        const sentences = para.match(/[^.!?]+[.!?]+\s*/g) || [para];
        let current = "";
        for (const sentence of sentences) {
          if ((current + sentence).length > 1200 && current.length > 0) {
            result.push(current.trim());
            current = sentence;
          } else {
            current += sentence;
          }
        }
        if (current.trim().length > 0) result.push(current.trim());
      }
    }
    return result.length > 0 ? result : [text.slice(0, 1200)];
  }

  function cleanForSpeech(text: string): string {
    return text
      .replace(/```[\s\S]*?```/g, ' (code block) ')
      .replace(/`([^`]+)`/g, '$1')
      .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
      .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
      .replace(/[#*_>~]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function getPreferredVoice(): SpeechSynthesisVoice | undefined {
    if (typeof window === "undefined" || !window.speechSynthesis) return undefined;
    const voices = window.speechSynthesis.getVoices();
    return voices.find(v =>
      v.name.includes('Female') || v.name.includes('Samantha') || v.name.includes('Google US English')
    ) || voices.find(v => v.lang.startsWith('en'));
  }

  /** Start live speechSynthesis narration for the current chapter (fallback). */
  function startLiveNarration() {
    if (typeof window === "undefined" || !window.speechSynthesis) return;
    const state = usePlayerStore.getState();
    const chapter = state.chapters[state.chapterIndex];
    if (!chapter) return;

    window.speechSynthesis.cancel();
    speakingLiveRef.current = true;
    setUsingLiveNarration(true);

    paragraphsRef.current = splitIntoParagraphs(chapter.cleanedText);
    paragraphIndexRef.current = 0;

    const speakNext = () => {
      if (!speakingLiveRef.current) return;
      const paras = paragraphsRef.current;
      const idx = paragraphIndexRef.current;

      if (idx >= paras.length) {
        speakingLiveRef.current = false;
        setUsingLiveNarration(false);
        if (usePlayerStore.getState().isPlaying) {
          usePlayerStore.getState().nextChapter();
        }
        return;
      }

      const text = cleanForSpeech(paras[idx]);
      if (!text) {
        paragraphIndexRef.current++;
        speakNext();
        return;
      }

      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = usePlayerStore.getState().playbackRate;
      utterance.pitch = 1.0;
      utterance.volume = usePlayerStore.getState().muted ? 0 : usePlayerStore.getState().volume;
      const voice = getPreferredVoice();
      if (voice) utterance.voice = voice;

      utterance.onend = () => {
        if (!speakingLiveRef.current) return;
        paragraphIndexRef.current++;
        if (usePlayerStore.getState().isPlaying) {
          speakNext();
        }
      };
      utterance.onerror = () => {
        speakingLiveRef.current = false;
        setUsingLiveNarration(false);
        usePlayerStore.getState().pause();
      };

      window.speechSynthesis.speak(utterance);
    };

    setTimeout(speakNext, 100);
  }

  /** Trigger TTS generation for a chapter via the API. Returns the audioUrl on success. */
  async function generateChapterAudio(audiobookId: string, chapterId: string): Promise<string | null> {
    try {
      const res = await fetch(`/api/audiobooks/${audiobookId}/chapters/${chapterId}/generate`, {
        method: 'POST',
      });
      if (!res.ok) return null;
      const data = await res.json();
      if (data.audioUrl && data.status === 'ready') {
        updateChapterStatus(chapterId, 'ready', data.audioUrl);
        return data.audioUrl;
      }
      return null;
    } catch {
      updateChapterStatus(chapterId, 'failed');
      return null;
    }
  }

  /** Pre-generate the next chapter in the background (fire-and-forget). */
  function preGenerateNextChapter() {
    const state = usePlayerStore.getState();
    if (!state.currentAudiobook) return;
    const nextIdx = state.chapterIndex + 1;
    if (nextIdx >= state.chapters.length) return;
    const nextCh = state.chapters[nextIdx];
    if (nextCh && nextCh.status === 'pending') {
      // Fire-and-forget — don't await, don't block current playback
      generateChapterAudio(state.currentAudiobook.id, nextCh.id).catch(() => {});
    }
  }

  // When chapter changes: set up playback
  useEffect(() => {
    if (!currentAudiobook) return;
    const chapter = chapters[chapterIndex];
    if (!chapter) return;

    // Stop any live narration
    speakingLiveRef.current = false;
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
    }
    setUsingLiveNarration(false);

    const a = audioRef.current;
    if (!a) return;

    if (chapter.status === 'ready' && chapter.audioUrl) {
      // Play the stored audio file
      setNarrating(false);
      a.src = chapter.audioUrl;
      a.load();
      setDuration(chapter.durationSeconds ?? 0);
    } else if (chapter.status === 'pending') {
      // Need to generate — will be triggered by the play effect below
      setNarrating(true);
      a.src = "";
    } else if (chapter.status === 'failed') {
      // Will fall back to live narration when play is pressed
      setNarrating(false);
      a.src = "";
    }
  }, [currentAudiobook, chapterIndex, chapters]);

  // Play / pause control
  useEffect(() => {
    if (!currentAudiobook) return;
    const a = audioRef.current;
    if (!a) return;
    const chapter = chapters[chapterIndex];
    if (!chapter) return;

    if (isPlaying) {
      if (chapter.status === 'ready' && chapter.audioUrl) {
        // Play stored audio
        if (a.paused) {
          a.play().catch(() => usePlayerStore.getState().pause());
        }
        // Pre-generate next chapter in the background
        preGenerateNextChapter();
      } else if (chapter.status === 'pending') {
        // Generate then play
        setNarrating(true);
        generateChapterAudio(currentAudiobook.id, chapter.id).then((url) => {
          if (url) {
            setNarrating(false);
            a.src = url;
            a.load();
            a.play().catch(() => usePlayerStore.getState().pause());
            preGenerateNextChapter();
          } else {
            // Generation failed — fall back to live narration
            setNarrating(false);
            startLiveNarration();
          }
        });
      } else if (chapter.status === 'failed') {
        // Fall back to live narration — but if live narration was already
        // active and merely paused (from a previous play/pause cycle on this
        // chapter), resume it in place rather than restarting from paragraph 0.
        if (speakingLiveRef.current && typeof window !== "undefined" && window.speechSynthesis?.paused) {
          window.speechSynthesis.resume();
        } else {
          startLiveNarration();
        }
      } else if (chapter.status === 'generating') {
        // Another request is actively generating this chapter's audio.
        // Wait for it to finish (poll the chapter's status) instead of
        // instantly falling back to the low-quality browser voice — real
        // TTS audio is likely to be ready soon.
        setNarrating(true);
        const chapterId = chapter.id;
        const pollForCompletion = async () => {
          const maxAttempts = 20; // ~20 x 2s = 40 seconds of patience before giving up
          for (let attempt = 0; attempt < maxAttempts; attempt++) {
            await new Promise(resolve => setTimeout(resolve, 2000));
            // Re-check current state — the user may have paused, skipped, or the
            // chapter may no longer be the active one by the time this resolves.
            const state = usePlayerStore.getState();
            if (!state.isPlaying || state.chapters[state.chapterIndex]?.id !== chapterId) {
              return; // bail — situation changed, don't force stale playback
            }
            const current = state.chapters.find(c => c.id === chapterId);
            if (current?.status === 'ready' && current.audioUrl) {
              setNarrating(false);
              const aa = audioRef.current;
              if (aa) {
                aa.src = current.audioUrl;
                aa.load();
                aa.play().catch(() => usePlayerStore.getState().pause());
              }
              preGenerateNextChapter();
              return;
            }
            if (current?.status === 'failed') break;
          }
          // Generation didn't finish in a reasonable time (or failed) — now
          // it's reasonable to fall back to live narration.
          setNarrating(false);
          // Re-check state one more time before starting fallback
          const state = usePlayerStore.getState();
          if (state.isPlaying && state.chapters[state.chapterIndex]?.id === chapterId) {
            startLiveNarration();
          }
        };
        pollForCompletion();
      }
    } else {
      // Pause
      if (!a.paused) a.pause();
      if (speakingLiveRef.current && typeof window !== "undefined" && window.speechSynthesis) {
        // Use pause() instead of cancel() for live narration — preserves the
        // current utterance's position so resume() continues from where it
        // left off, rather than restarting the chapter from the beginning.
        // Do NOT reset speakingLiveRef or setUsingLiveNarration(false) here —
        // the narration session should remain "paused," not torn down.
        window.speechSynthesis.pause();
      }
    }
  }, [isPlaying, currentAudiobook, chapterIndex, chapters]);

  // Sync <audio> element time updates → store
  useEffect(() => {
    const a = audioRef.current;
    if (!a) return;
    const onTimeUpdate = () => {
      if (!usePlayerStore.getState().usingLiveNarration) {
        setCurrentTime(a.currentTime);
      }
    };
    const onLoadedMetadata = () => {
      if (a.duration && isFinite(a.duration)) {
        setDuration(a.duration);
      }
    };
    const onEnded = () => {
      const state = usePlayerStore.getState();
      if (state.chapterIndex < state.chapters.length - 1) {
        state.nextChapter();
      } else {
        state.pause();
      }
    };
    a.addEventListener('timeupdate', onTimeUpdate);
    a.addEventListener('loadedmetadata', onLoadedMetadata);
    a.addEventListener('ended', onEnded);
    return () => {
      a.removeEventListener('timeupdate', onTimeUpdate);
      a.removeEventListener('loadedmetadata', onLoadedMetadata);
      a.removeEventListener('ended', onEnded);
    };
  }, [setCurrentTime, setDuration]);

  // playbackRate → audio element (and live narration reads it per-utterance)
  useEffect(() => {
    const a = audioRef.current;
    if (a) a.playbackRate = playbackRate;
  }, [playbackRate]);

  // volume / muted → audio element
  useEffect(() => {
    const a = audioRef.current;
    if (a) {
      a.volume = muted ? 0 : volume;
      a.muted = muted;
    }
  }, [volume, muted]);

  // Seek → actually move the <audio> element's playhead.
  //
  // We subscribe to the store directly (getState + subscribe) rather than
  // using a React useEffect dependency on `currentTime`, because currentTime
  // changes on EVERY timeupdate tick (many times per second). Reacting to
  // every change would cause an infinite loop: audio fires timeupdate →
  // store updates currentTime → effect fires → sets audio.currentTime →
  // audio fires timeupdate → ...
  //
  // Instead, we track the last time WE wrote to audio.currentTime and only
  // propagate store → audio when the difference is large enough that it
  // can't have come from a natural timeupdate tick (i.e., it came from a
  // seek() call, not from the audio element itself).
  useEffect(() => {
    const SEEK_THRESHOLD = 1.5; // seconds — normal playback never jumps this far per tick
    let lastWrittenTime = -1;

    const unsubscribe = usePlayerStore.subscribe((state) => {
      const a = audioRef.current;
      if (!a || !a.src) return;

      const storeTime = state.currentTime;
      // If the store's time differs from what audio reports by more than the
      // threshold, it was a user seek — write it back to the element.
      const delta = Math.abs(storeTime - a.currentTime);
      if (delta > SEEK_THRESHOLD && Math.abs(storeTime - lastWrittenTime) > 0.1) {
        a.currentTime = storeTime;
        lastWrittenTime = storeTime;
      }
    });

    return unsubscribe;
  }, []); // empty deps — subscription is created once and cleaned up on unmount

  // Virtual elapsed-time clock for live narration (when no real audio is playing)
  useEffect(() => {
    if (!currentAudiobook || !isPlaying) {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      return;
    }
    const state = usePlayerStore.getState();
    if (state.usingLiveNarration === false) {
      // Real audio is playing — currentTime comes from the <audio> element's
      // timeupdate events, no need for a RAF clock.
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      return;
    }

    lastTickRef.current = performance.now();
    const tick = (now: number) => {
      const dt = (now - lastTickRef.current) / 1000;
      lastTickRef.current = now;
      if (typeof window !== "undefined" && window.speechSynthesis && window.speechSynthesis.speaking && !window.speechSynthesis.paused) {
        const s = usePlayerStore.getState();
        const ch = s.chapters[s.chapterIndex];
        if (ch) {
          const est = ch.durationSeconds ?? Math.round((ch.cleanedText.split(/\s+/).length / 155) * 60);
          const newTime = s.currentTime + dt * s.playbackRate;
          if (newTime >= est) {
            setCurrentTime(est);
          } else {
            setCurrentTime(newTime);
          }
        }
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [isPlaying, currentAudiobook, playbackRate, setCurrentTime]);

  // Persist progress to server periodically
  useEffect(() => {
    if (!currentAudiobook) return;
    const persist = async () => {
      const s = usePlayerStore.getState();
      if (!s.currentAudiobook) return;
      try {
        await fetch(`/api/audiobooks/${s.currentAudiobook.id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            progressChapter: s.chapterIndex,
            progressCharOffset: Math.floor(s.currentTime),
          }),
        });
      } catch {
        // best-effort
      }
    };
    const id = setInterval(persist, 5000);
    return () => clearInterval(id);
  }, [currentAudiobook]);

  // Sleep timer watcher
  useEffect(() => {
    if (!sleepTimerEndsAt) return;
    const id = setInterval(() => {
      if (Date.now() >= sleepTimerEndsAt) {
        pause();
        const a = audioRef.current;
        if (a) a.pause();
        if (typeof window !== "undefined" && window.speechSynthesis) {
          window.speechSynthesis.cancel();
        }
        speakingLiveRef.current = false;
        usePlayerStore.getState().clearSleepTimer();
      }
    }, 1000);
    return () => clearInterval(id);
  }, [sleepTimerEndsAt, pause]);

  // Media Session API
  useEffect(() => {
    if (typeof window === "undefined" || !("mediaSession" in navigator) || !currentAudiobook) return;
    const chapter = chapters[chapterIndex];
    if (!chapter) return;
    try {
      navigator.mediaSession.metadata = new MediaMetadata({
        title: `${chapter.title} — ${currentAudiobook.title}`,
        artist: currentAudiobook.author || "Unknown author",
        album: "ARIA Audiobooks",
      });
      navigator.mediaSession.setActionHandler("play", () => usePlayerStore.getState().play());
      navigator.mediaSession.setActionHandler("pause", () => usePlayerStore.getState().pause());
      navigator.mediaSession.setActionHandler("previoustrack", () => usePlayerStore.getState().prevChapter());
      navigator.mediaSession.setActionHandler("nexttrack", () => usePlayerStore.getState().nextChapter());
      navigator.mediaSession.setActionHandler("seekbackward", () => usePlayerStore.getState().skip(-15));
      navigator.mediaSession.setActionHandler("seekforward", () => usePlayerStore.getState().skip(30));
    } catch {
      /* ignore */
    }
  }, [currentAudiobook, chapterIndex, chapters]);

  return null;
}
